services:
  pipeline:
    build:
      context: .
      shm_size: '12gb'
    shm_size: '12gb'
    volumes:
      - source: data
        target: /app/src/data
        type: bind
        bind:
            create_host_path: true
volumes:
  data: